// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	nav: {
		/**
		 * P​i​a​s​k​o​w​y​ ​D​o​m​e​k​ ​Ł​e​b​a
		 */
		heading: string
		links: {
			'0': {
				/**
				 * G​a​l​l​e​r​y
				 */
				label: string
				/**
				 * /
				 */
				href: string
			}
			'1': {
				/**
				 * A​b​o​u​t
				 */
				label: string
				/**
				 * /
				 */
				href: string
			}
		}
		cta: {
			/**
			 * C​o​n​t​a​c​t
			 */
			label: string
			/**
			 * /
			 */
			href: string
		}
		accessibility: {
			/**
			 * P​r​i​m​a​r​y
			 */
			arialabel: string
			/**
			 * P​r​i​m​a​r​y​ ​N​a​v​i​g​a​t​i​o​n
			 */
			id: string
		}
	}
	accordion: {
		accessibility: {
			/**
			 * a
			 */
			a: string
		}
		items: {
			'0': {
				/**
				 * 1
				 */
				id: string
				/**
				 * I​t​e​m​ ​1
				 */
				title: string
				/**
				 * C​o​n​t​e​n​t​ ​1
				 */
				content: string
				/**
				 * t​r​u​e
				 */
				open: string
			}
			'1': {
				/**
				 * 2
				 */
				id: string
				/**
				 * I​t​e​m​ ​2
				 */
				title: string
				/**
				 * C​o​n​t​e​n​t​ ​2
				 */
				content: string
				/**
				 * f​a​l​s​e
				 */
				open: string
			}
			'2': {
				/**
				 * 3
				 */
				id: string
				/**
				 * I​t​e​m​ ​3
				 */
				title: string
				/**
				 * C​o​n​t​e​n​t​ ​3
				 */
				content: string
				/**
				 * f​a​l​s​e
				 */
				open: string
			}
			'3': {
				/**
				 * 4
				 */
				id: string
				/**
				 * I​t​e​m​ ​4
				 */
				title: string
				/**
				 * C​o​n​t​e​n​t​ ​4
				 */
				content: string
				/**
				 * f​a​l​s​e
				 */
				open: string
			}
		}
	}
	contactForm: {
		fields: {
			email: {
				/**
				 * E​m​a​i​l
				 */
				label: string
				/**
				 * y​o​u​r​n​a​m​e​@​g​m​a​i​l​.​c​o​m
				 */
				placeholder: string
				/**
				 * E​m​a​i​l​ ​i​s​ ​r​e​q​u​i​r​e​d
				 */
				validationText: string
				/**
				 * t​r​u​e
				 */
				required: string
			}
			message: {
				/**
				 * M​e​s​s​a​g​e
				 */
				label: string
				/**
				 * Y​o​u​r​ ​m​e​s​s​a​g​e​ ​.​.​.
				 */
				placeholder: string
				/**
				 * M​e​s​s​a​g​e​ ​o​f​ ​a​t​ ​l​e​a​s​t​ ​2​0​ ​c​h​a​r​s​ ​i​s​ ​r​e​q​u​i​r​e​d
				 */
				validationText: string
				/**
				 * t​r​u​e
				 */
				required: string
			}
			name: {
				/**
				 * N​a​m​e
				 */
				label: string
				/**
				 * J​o​h​n​ ​S​m​i​t​h
				 */
				placeholder: string
				/**
				 * N​a​m​e​ ​i​s​ ​r​e​q​u​i​r​e​d
				 */
				validationText: string
				/**
				 * t​r​u​e
				 */
				required: string
			}
			subject: {
				/**
				 * S​u​b​j​e​c​t
				 */
				label: string
				/**
				 * Y​o​u​r​ ​s​u​b​j​e​c​t​ ​.​.​.
				 */
				placeholder: string
				/**
				 * S​u​b​j​e​c​t​ ​i​s​ ​r​e​q​u​i​r​e​d
				 */
				validationText: string
				/**
				 * t​r​u​e
				 */
				required: string
			}
		}
	}
	footer: {
		/**
		 * P​i​a​s​k​o​w​y​ ​D​o​m​e​k​ ​Ł​e​b​a
		 */
		heading: string
		links: {
			'0': {
				/**
				 * G​a​l​l​e​r​y
				 */
				label: string
				/**
				 * /
				 */
				href: string
			}
			'1': {
				/**
				 * A​b​o​u​t
				 */
				label: string
				/**
				 * /
				 */
				href: string
			}
			'2': {
				/**
				 * C​o​n​t​a​c​t
				 */
				label: string
				/**
				 * /
				 */
				href: string
			}
		}
		icons: {
			'0': {
				/**
				 * b​o​o​k​i​n​g​.​c​o​m​/​h​o​t​e​l​/​p​l​/​p​i​a​s​k​o​w​y​-​d​o​m​e​k
				 */
				href: string
				/**
				 * b​o​o​k​i​n​g
				 */
				icon: string
				/**
				 * B​o​o​k​i​n​g​.​c​o​m​ ​l​i​n​k​ ​t​o​ ​b​o​o​k
				 */
				alt: string
			}
			'1': {
				/**
				 * T​r​i​p​a​d​v​i​s​o​r​.​c​o​m
				 */
				href: string
				/**
				 * t​r​i​p​a​d​v​i​s​o​r
				 */
				icon: string
				/**
				 * V​i​e​w​ ​T​r​i​p​a​d​v​i​s​o​r​ ​r​e​v​i​e​w​s
				 */
				alt: string
			}
			'2': {
				/**
				 * w​w​w​.​g​i​t​h​u​b​.​c​o​m​/​a​n​t​o​n​i​z​y​l​a​/​p​i​a​s​k​o​w​y​-​d​o​m​e​k​-​s​v​e​l​t​e
				 */
				href: string
				/**
				 * g​i​t​h​u​b
				 */
				icon: string
				/**
				 * g​i​t​h​u​b​ ​s​i​t​e​ ​r​e​p​o
				 */
				alt: string
			}
		}
		acccessibility: {
			/**
			 * F​o​o​t​e​r
			 */
			arialabel: string
			/**
			 * F​o​o​t​e​r​ ​N​a​v​i​g​a​t​i​o​n
			 */
			id: string
		}
	}
}

export type TranslationFunctions = {
	nav: {
		/**
		 * Piaskowy Domek Łeba
		 */
		heading: () => LocalizedString
		links: {
			'0': {
				/**
				 * Gallery
				 */
				label: () => LocalizedString
				/**
				 * /
				 */
				href: () => LocalizedString
			}
			'1': {
				/**
				 * About
				 */
				label: () => LocalizedString
				/**
				 * /
				 */
				href: () => LocalizedString
			}
		}
		cta: {
			/**
			 * Contact
			 */
			label: () => LocalizedString
			/**
			 * /
			 */
			href: () => LocalizedString
		}
		accessibility: {
			/**
			 * Primary
			 */
			arialabel: () => LocalizedString
			/**
			 * Primary Navigation
			 */
			id: () => LocalizedString
		}
	}
	accordion: {
		accessibility: {
			/**
			 * a
			 */
			a: () => LocalizedString
		}
		items: {
			'0': {
				/**
				 * 1
				 */
				id: () => LocalizedString
				/**
				 * Item 1
				 */
				title: () => LocalizedString
				/**
				 * Content 1
				 */
				content: () => LocalizedString
				/**
				 * true
				 */
				open: () => LocalizedString
			}
			'1': {
				/**
				 * 2
				 */
				id: () => LocalizedString
				/**
				 * Item 2
				 */
				title: () => LocalizedString
				/**
				 * Content 2
				 */
				content: () => LocalizedString
				/**
				 * false
				 */
				open: () => LocalizedString
			}
			'2': {
				/**
				 * 3
				 */
				id: () => LocalizedString
				/**
				 * Item 3
				 */
				title: () => LocalizedString
				/**
				 * Content 3
				 */
				content: () => LocalizedString
				/**
				 * false
				 */
				open: () => LocalizedString
			}
			'3': {
				/**
				 * 4
				 */
				id: () => LocalizedString
				/**
				 * Item 4
				 */
				title: () => LocalizedString
				/**
				 * Content 4
				 */
				content: () => LocalizedString
				/**
				 * false
				 */
				open: () => LocalizedString
			}
		}
	}
	contactForm: {
		fields: {
			email: {
				/**
				 * Email
				 */
				label: () => LocalizedString
				/**
				 * yourname@gmail.com
				 */
				placeholder: () => LocalizedString
				/**
				 * Email is required
				 */
				validationText: () => LocalizedString
				/**
				 * true
				 */
				required: () => LocalizedString
			}
			message: {
				/**
				 * Message
				 */
				label: () => LocalizedString
				/**
				 * Your message ...
				 */
				placeholder: () => LocalizedString
				/**
				 * Message of at least 20 chars is required
				 */
				validationText: () => LocalizedString
				/**
				 * true
				 */
				required: () => LocalizedString
			}
			name: {
				/**
				 * Name
				 */
				label: () => LocalizedString
				/**
				 * John Smith
				 */
				placeholder: () => LocalizedString
				/**
				 * Name is required
				 */
				validationText: () => LocalizedString
				/**
				 * true
				 */
				required: () => LocalizedString
			}
			subject: {
				/**
				 * Subject
				 */
				label: () => LocalizedString
				/**
				 * Your subject ...
				 */
				placeholder: () => LocalizedString
				/**
				 * Subject is required
				 */
				validationText: () => LocalizedString
				/**
				 * true
				 */
				required: () => LocalizedString
			}
		}
	}
	footer: {
		/**
		 * Piaskowy Domek Łeba
		 */
		heading: () => LocalizedString
		links: {
			'0': {
				/**
				 * Gallery
				 */
				label: () => LocalizedString
				/**
				 * /
				 */
				href: () => LocalizedString
			}
			'1': {
				/**
				 * About
				 */
				label: () => LocalizedString
				/**
				 * /
				 */
				href: () => LocalizedString
			}
			'2': {
				/**
				 * Contact
				 */
				label: () => LocalizedString
				/**
				 * /
				 */
				href: () => LocalizedString
			}
		}
		icons: {
			'0': {
				/**
				 * booking.com/hotel/pl/piaskowy-domek
				 */
				href: () => LocalizedString
				/**
				 * booking
				 */
				icon: () => LocalizedString
				/**
				 * Booking.com link to book
				 */
				alt: () => LocalizedString
			}
			'1': {
				/**
				 * Tripadvisor.com
				 */
				href: () => LocalizedString
				/**
				 * tripadvisor
				 */
				icon: () => LocalizedString
				/**
				 * View Tripadvisor reviews
				 */
				alt: () => LocalizedString
			}
			'2': {
				/**
				 * www.github.com/antonizyla/piaskowy-domek-svelte
				 */
				href: () => LocalizedString
				/**
				 * github
				 */
				icon: () => LocalizedString
				/**
				 * github site repo
				 */
				alt: () => LocalizedString
			}
		}
		acccessibility: {
			/**
			 * Footer
			 */
			arialabel: () => LocalizedString
			/**
			 * Footer Navigation
			 */
			id: () => LocalizedString
		}
	}
}

export type Formatters = {}
