// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'pl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ ​P​l​e​a​s​e​ ​l​e​a​v​e​ ​a​ ​s​t​a​r​ ​i​f​ ​y​o​u​ ​l​i​k​e​ ​t​h​i​s​ ​p​r​o​j​e​c​t​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​i​v​a​n​h​o​f​e​r​/​t​y​p​e​s​a​f​e​-​i​1​8​n
	 */
	HI: string
	nav: {
		/**
		 * P​i​a​s​k​o​w​y​ ​D​o​m​e​k​ ​Ł​e​b​a
		 */
		heading: string
		links: {
			'0': {
				/**
				 * G​a​l​l​e​r​y
				 */
				label: string
				/**
				 * /
				 */
				href: string
			}
			'1': {
				/**
				 * A​b​o​u​t
				 */
				label: string
				/**
				 * /
				 */
				href: string
			}
		}
		cta: {
			/**
			 * C​o​n​t​a​c​t
			 */
			label: string
			/**
			 * /
			 */
			href: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Hi Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 */
	HI: () => LocalizedString
	nav: {
		/**
		 * Piaskowy Domek Łeba
		 */
		heading: () => LocalizedString
		links: {
			'0': {
				/**
				 * Gallery
				 */
				label: () => LocalizedString
				/**
				 * /
				 */
				href: () => LocalizedString
			}
			'1': {
				/**
				 * About
				 */
				label: () => LocalizedString
				/**
				 * /
				 */
				href: () => LocalizedString
			}
		}
		cta: {
			/**
			 * Contact
			 */
			label: () => LocalizedString
			/**
			 * /
			 */
			href: () => LocalizedString
		}
	}
}

export type Formatters = {}
